### PR TITLE
Changed to reset name on all deleted and cleared channel entries

### PR DESCRIPTION
**Pull request by footloosejava**
#65

The problem with the import order happens because the old data (name) is still on all the entries in the chList[1024]. So when it finds an unused slot with the same name, it uses that slot instead of the next available slot. See:

```
foundIndex = ChannelForm.data.FindIndexForName(name);
if (foundIndex == -1)
{
		foundIndex = ChannelForm.data.GetMinIndex();
...
```

So, by making sure that the name is reset on delete, clear, and import(clearall), then the index for name won't be found and the minIndex will be used instead. 

This ensures that the order of entries is the same as found in the import CSV file

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I will test and merge if there are no errors

**Comment by rogerclarkmelbourne** [comment]
There is something strange with this PR

Its showing that you added commport selector, but its already in the codebase

I think you may need to pull from my master and then recommit the change somehow, as I suspect your repo is not up to date.

**Comment by footloosejava** [comment]
Sorry. I moved took it out of my dev branch and moved it to its own branch. I'll re send a new pull request shortly.

**Comment by rogerclarkmelbourne** [comment]
OK

Thanks. Its best if the merge is clean

**Pull request closed without merging**
