### PR TITLE
Screenshot blue bg and x2 scaling

### PR DESCRIPTION
**Pull request by f1rmb**
Hi Roger,

   I don't know if it compiles, I need to fix latest changes in the Linux's cs project file. But I've tested outside, and it works.

Cheers.

### CODE REVIEW

**Comment by f1rmb** [comment]
Ignore the shell script, it seems I messed up the master branch locally.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

I'll probably remove the update to the .sh file, so that this commit only changes the screengrab.

I'll also test it and make sure it compiles ;-) and that the image quality is OK after the interpolation.

Thanks

**Comment by rogerclarkmelbourne** [comment]
LOL we cross posted about the .sh

**Comment by f1rmb** [comment]
;-)

Here, with the resize parameter, it's like pixel copy, no smotthing/antialising effects.

**Comment by rogerclarkmelbourne** [comment]
It almost worked ;-)

I've bug fixed a few things

image

I'm going to  investigate whether the other scaling options give reasonable image quality.

**Comment by f1rmb** [comment]
Cool! ;-)

**Comment by rogerclarkmelbourne** [comment]
I think graphics.InterpolationMode = InterpolationMode.Default; is possibly better

image

**Comment by rogerclarkmelbourne** [comment]
Actually... No

Nearest Neighbour is better

image

**Comment by f1rmb** [comment]
I personnaly prefer sharpness

image

**Comment by f1rmb** [comment]
:-D

**Comment by rogerclarkmelbourne** [comment]
Yes.

Thats what I've committed.

If anyone wants to smooth it they can, but its not possible restore the sharpness if I used the interpolated modes.

Thanks.

I've just manually copied the .cs file as it was the only way not to include adding and removing the shell script.

So I'll close this PR now even though it looks like I've not merged it.

**Comment by f1rmb** [comment]
No problem, me and my broken branches :-D

**Pull request closed without merging**
